'''
Problem Statement:
Each new term in the Fibonacci sequence
is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million,
find the sum of the even-valued terms.

'''

fib = [0, 1]
fib_max = 4000000
fib_s = 0

# Fill List with fibonacci numbers
# And sum even numbers
while fib[-1] < 4000000:
    if fib[-1] % 2 == 0:
        fib_s += fib[-1]
    fib.append(fib[-1] + fib[-2])
print(fib_s)
